### ISSUE TITLE
Empty error message when signing

### ISSUE THREAD

**Issue by stevenkhong** [Zondax/ledger-go#33]
I'm signing a transaction using `gaiad` binary (v13.0.1) on the CLI, but ran into an error with no error message. Checked with another binary (`kujirad`, v0.9.1), same issue. Tried upgrading to ledger-go `v0.14.3` with no change in behaviour. I suspect its related to this new version of Ledger OS.

```
gaiad tx bank send cosmos1…2d cosmos1…2d 1uatom --from ledger 

Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
Error: 
Usage:
  gaiad tx bank send [from_key_or_address] [to_address] [amount] [flags]

Flags:
…
```

Some debugging led me to this [line](https://github.com/Zondax/ledger-go/blob/2905003530da05e9b63b72625f942075b0497cd6/ledger_hid.go#L248):
>```golang
> if sw != 0x9000 {
>   return response[:swOffset], errors.New(ErrorMessage(sw))
>}

`sw` had a value of `0x6984`.

Setup:
ledger-go `v0.14.3`
ledger `Nano X`
ledger OS `v2.2.3`
Cosmos App `v2.34.12`

**Comment by ftheirs** [comment]
Are you trying to sign using `direct` mode because it's not supported

**Comment by stevenkhong** [comment]
> Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.

Supplying `--sign-mode amino-json` results in the same behaviour. The log above just says that it is already using `amino-json`. So no, we're not trying to sign using `direct` mode.

**Comment by ftheirs** [comment]
Hi @stevenkhong, I was able to verify the transaction in NanoS+ and NanoX. Both were working just fine
```
gaiad tx bank send cosmos1..eg cosmos1..y8 1uatom --from ledger
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
{"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"cosmos1..eg","to_address":"cosmos1..y8","amount":[{"denom":"uatom","amount":"1"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
Error: [APDU_CODE_COMMAND_NOT_ALLOWED] Command not allowed / User Rejected (no current EF)
```

From gaia `v13.0.1`, I just updates `ledger-cosmos-go` package. This will trigger an update in ledger-go and hid packages.
```
-       github.com/cosmos/ledger-cosmos-go v0.12.2 // indirect
+       github.com/cosmos/ledger-cosmos-go v0.12.4 // indirect
```
For NanoX I checked with the firmware version `v2.2.2` and `v.2.2.3` and both were working. Can you run any other command to interact with the device? This one should trigger a review menu on the Ledger
`gaiad keys add nanoX --ledger `

**Comment by stevenkhong** [comment]
@ftheirs magic, looks like hid package upgrade did the trick. Verified it works, thank you!
